// Airport dining, scraped. Generated by tools/dining/run.py -- do not edit.
//
// WHAT THIS IS FOR: telling somebody with a layover what they can actually eat,
// which is a question about SECURITY ZONES before it is a question about food.
// A restaurant on the wrong side of passport control is not a lunch option for a
// connecting passenger, it is a missed flight.
//
// SO READ isAirside WITH securityBasis, ALWAYS:
//
//   "explicit"  the airport publishes the zone per outlet. Trust it.
//   "inferred"  we deduced it, e.g. from a gate number. DO NOT present as fact
//               until the inference has been measured against an explicit source.
//   "unknown"   nobody knows. Show "location unclear"; never guess.
//
// securityRaw is the source's own words, kept beside the boolean so a mis-parse
// is visible rather than silently inverting what the column means.
//
// HOURS ARE VERBATIM STRINGS in the airport's local time, with whatever dialect
// the source uses -- "07:00 - 23:00", en dashes, "(Last order: 20:30)". They are
// deliberately not parsed by the scraper. Parse them here, against the airport's
// timezone from airports.ts, or show them as they came.
//
// SOURCES
//   HKG    76 outlets   source: https://www.hongkongairport.com/iwov-resources/custom/json/shops_en.json   their last update: 2026-09-04 17:27:48   fetched: 2026-09-06T11:25:44Z

export type Dining = {
  airport: string;
  name: string;
  sourceId: string;
  terminalRaw: string;
  terminal: string;
  level: string;
  area: string;
  gateHint: string;
  isAirside: boolean | null;
  securityRaw: string;
  securityBasis: 'explicit' | 'inferred' | 'unknown';
  categoryRaw: string;
  category: string;
  hoursRaw: string;
  is24H: boolean;
  lat: number | null;
  lon: number | null;
};

type Row = [string, string, string, string, string, string, string, string, boolean | null, string, 'explicit' | 'inferred' | 'unknown', string, string, string, boolean, number | null, number | null];

const ROWS: Row[] = [
  ["HKG", "Popeyes Louisiana Kitchen", "6W524C", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "fastf|veget", "fast_food|vegetarian", "07:00 - 21:00 (Last order: 20:30)", false, 22.313066405887156, 113.92684507491202],
  ["HKG", "PRET A MANGER", "5T028", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:30 - 23:00", false, 22.316958, 113.935401],
  ["HKG", "PRET A MANGER", "6N504B", "T1", "T1", "L6", "Terminal 1", "6", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:00 - 23:30", false, 22.317290554103966, 113.93369897689921],
  ["HKG", "PRET A MANGER", "6Z509", "T1", "T1", "L6", "Terminal 1", "25", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:00 - 23:30", false, 22.314090772902734, 113.9311587294926],
  ["HKG", "GODIVA Café", "dining_desse_00008", "T1", "T1", "L7", "Terminal 1", "", false, "Non-restricted Area", "explicit", "desse|veget", "dessert|vegetarian", "07:00 – 24:00", false, 22.317121642918583, 113.9349066258625],
  ["HKG", "Master Hung", "6W524A", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "chine|fastf", "chinese|fast_food", "07:00 - 22:00 (Last order: 21:30)", false, 22.313154156988336, 113.92684626810778],
  ["HKG", "Take Eat Easy", "6MC055", "T1", "T1", "L6", "Midfield Concourse", "201-230", true, "Restricted Area", "explicit", "chine", "chinese", "05:30 - 23:00", false, 22.310179038622838, 113.91806080213114],
  ["HKG", "nodi", "dining_weste_00010", "T1", "T1", "L6", "Midfield Concourse", "214", true, "Restricted Area", "explicit", "weste", "western", "07:00 – 23:00", false, 22.308258079096866, 113.91831736068451],
  ["HKG", "Orchid Padaria Café Express", "3TL018", "T2", "T2", "L3", "Terminal 2", "", false, "Non-restricted Area", "explicit", "chine|fastf", "chinese|fast_food", "07:00-23:00", false, 22.3156534859126, 113.93710800315196],
  ["HKG", "nodi | Moleskine", "6W530", "T1", "T1", "L6", "Terminal 1", "60", true, "Restricted Area", "explicit", "weste", "western", "07:00 – 23:00", false, 22.313283567453368, 113.92680033138338],
  ["HKG", "Jardin de Jade", "7E111", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "chine", "chinese", "07:00 - 23:30 (23:00 last order)", false, 22.315673, 113.933347],
  ["HKG", "STARBUCKS", "dining_veget_00022", "T1", "T1", "L6", "Terminal 1", "6", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:00 - 23:00", false, 22.317351180461415, 113.93367724395749],
  ["HKG", "STARBUCKS", "dining_veget_00023", "T1", "T1", "L6", "Terminal 1", "", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "07:00 - 23:00", false, 22.31336271525789, 113.92660107466756],
  ["HKG", "STARBUCKS", "dining_veget_00020", "T1", "T1", "L6", "Midfield Concourse", "206", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:00 - 24:00", false, 22.311820771889735, 113.91712487480923],
  ["HKG", "STARBUCKS", "dining_veget_00021", "T1", "T1", "L5", "T1 Satellite Concourse", "13-21", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:30 - 23:00", false, 22.317046168909084, 113.93030729678527],
  ["HKG", "STARBUCKS", "dining_veget_00019", "T1", "T1", "L7", "Terminal 1", "", false, "Non-restricted Area", "explicit", "veget|weste", "vegetarian|western", "05:30 - 23:00", false, 22.31517585386647, 113.93441634436462],
  ["HKG", "STARBUCKS", "6Y585", "T1", "T1", "L6", "Terminal 1", "44", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "06:00 - 23:00", false, 22.311048, 113.926418],
  ["HKG", "GELATO COMBO", "dining_desse_00014", "T1", "T1", "L6", "Terminal 1", "28", true, "Restricted Area", "explicit", "desse", "dessert", "07:00 - 23:00", false, 22.314137790553026, 113.93073182063046],
  ["HKG", "Men Wah Bing Teng", "dining_chine_00019", "T1", "T1", "L6", "Terminal 1", "11", true, "Restricted Area", "explicit", "chine", "chinese", "00:00 - 24:00", true, 22.314595303246843, 113.93273092898023],
  ["HKG", "Lime Garden (Sky)+", "8T011", "T1", "T1", "L8", "Terminal 1", "", false, "Non-restricted Area", "explicit", "asian", "asian", "06:30 - 00:30", false, 22.315572, 113.934324],
  ["HKG", "can.teen", "7T090", "T1", "T1", "L7", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "05:30 - 23:00", false, 22.315413, 113.934316],
  ["HKG", "Ho Hung Kee", "5T160", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "07:00 - 23:30", false, 22.315480394173406, 113.93600702031944],
  ["HKG", "%Arabica", "dining_weste_00012", "T1", "T1", "L6", "Terminal 1", "10", true, "Restricted Area", "explicit", "weste", "western", "00:00 - 24:00", true, 22.315079977819696, 113.93302837730786],
  ["HKG", "Gourmet Focus Group", "dining_fastf_00035", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "asian", "asian", "07:00 - 23:00 (Last order: 22:30)", false, 22.31247919856121, 113.92706137530948],
  ["HKG", "NUTTEA", "5T052", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.315814067319973, 113.93544525213515],
  ["HKG", "McDonald's® & McCafé®", "dining_fastf_00030", "T1", "T1", "L6", "Terminal 1", "11", true, "Restricted Area", "explicit", "fastf|veget", "fast_food|vegetarian", "00:00 - 24:00", true, 22.314583184020854, 113.93268564943685],
  ["HKG", "McDonald's® & McCafé®", "8T005A", "T1", "T1", "L8", "Terminal 1", "", false, "Non-restricted Area", "explicit", "fastf|veget", "fast_food|vegetarian", "00:00 - 24:00", true, 22.31512, 113.934563],
  ["HKG", "McDonald's® & McCafé®", "7TL056", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "fastf|veget", "fast_food|vegetarian", "00:00 - 24:00", true, 22.316565412667703, 113.9392028762619],
  ["HKG", "One Minute Gourmet", "dining_asian_00012", "T1", "T1", "L6", "Terminal 1", "60", true, "Restricted Area", "explicit", "asian|desse|fastf|veget", "asian|dessert|fast_food|vegetarian", "06:00 - 23:00 (Last order: 22:30)", false, 22.312481951430023, 113.92706470868055],
  ["HKG", "One Minute Gourmet", "6W524F", "T1", "T1", "L6", "Terminal 1", "40", true, "Restricted Area", "explicit", "asian|desse|fastf|veget", "asian|dessert|fast_food|vegetarian", "06:00 - 23:00 (Last order: 22:30)", false, 22.313198, 113.926839],
  ["HKG", "PUTIEN", "7E181", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "chine", "chinese", "00:00 - 24:00", true, 22.315415305541162, 113.93393629260171],
  ["HKG", "Konjiki Hototogisu", "5T060", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "asian", "asian", "07:00 - 23:00", false, 22.315365566831336, 113.9355912486277],
  ["HKG", "Urban Coffee Roaster", "6W570A", "T1", "T1", "L6", "Terminal 1", "40", true, "Restricted Area", "explicit", "weste", "western", "06:00 - 23:00", false, 22.312371451566484, 113.92713871217629],
  ["HKG", "Lin Heung Lau", "8T025", "T1", "T1", "L8", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "00:00 - 24:00", true, 22.31536125718205, 113.93447311992685],
  ["HKG", "INTERVALS Sky Bar & Restaurant", "dining_weste_00006", "SB", "SB", "L9", "Sky Bridge", "", true, "Restricted Area", "explicit", "weste", "western", "07:00 - 02:00", false, 22.31521338828529, 113.93176339730296],
  ["HKG", "Milk Cafe", "7TL048", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "chine|veget", "chinese|vegetarian", "00:00 - 24:00", true, 22.316645481424988, 113.93942454967979],
  ["HKG", "Nippon Ramen", "dining_fastf_00034", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "asian|fastf", "asian|fast_food", "07:00 - 23:00 (Last order: 22:30)", false, 22.31311203707422, 113.92685000281834],
  ["HKG", "Burger King", "6W564C", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "fastf", "fast_food", "06:30 - 23:00 (Last order: 22:30)", false, 22.312582, 113.927022],
  ["HKG", "Hung's Delicacies", "5T151", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "00:00 - 24:00", true, 22.315946067177812, 113.93584330641855],
  ["HKG", "Cupping Room Coffee Roasters", "7TL043", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "baker|desse|veget|weste", "bakery|dessert|vegetarian|western", "06:00 – 23:00", false, 22.316727376195995, 113.9390578323589],
  ["HKG", "Ritazza", "dining_weste_00007", "T1", "T1", "L6", "Terminal 1", "40", true, "Restricted Area", "explicit", "weste", "western", "06:00 - 21:00 (Last order: 20:30)", false, 22.31258928799202, 113.92708974776913],
  ["HKG", "Yung Kee", "6W564E", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "chine|fastf|veget", "chinese|fast_food|vegetarian", "12:00 - 22:00 (Last order: 21:15)", false, 22.312701, 113.926924],
  ["HKG", "Lady M New York", "7E151", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "desse|veget", "dessert|vegetarian", "07:00 - 23:00", false, 22.314259, 113.93417],
  ["HKG", "Sleep Well Eat More", "dining_desse_00015", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "desse", "dessert", "07:00 - 23:00", false, 22.315309849439622, 113.93563889450276],
  ["HKG", "Jollibee", "7TL030", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "fastf", "fast_food", "00:00 - 24:00", true, 22.316960903960762, 113.93903753495806],
  ["HKG", "Tap + Brew", "dining_weste_00004", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "weste", "western", "12:00 - 23:00 (Last order: 22:30)", false, 22.31302376666781, 113.92685182738931],
  ["HKG", "RYU竜", "5T053", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "asian", "asian", "Mon-Thu: 07:00-24:00 Fri-Sun: 07:00-01:00", false, 22.315761772359007, 113.93540389943051],
  ["HKG", "Moon Thai Express", "dining_asian_00018", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "asian", "asian", "00:00 - 24:00", true, 22.315327964946704, 113.93395358651948],
  ["HKG", "KING BAKERY", "6Z512", "T1", "T1", "L6", "Terminal 1", "28", true, "Restricted Area", "explicit", "baker|veget|weste", "bakery|vegetarian|western", "06:00 - 00:00", false, 22.31412, 113.930684],
  ["HKG", "Tamjai SamGor Mixian", "7TL349", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "chine|veget", "chinese|vegetarian", "06:00 – 23:00", false, 22.317013656267974, 113.93916504225449],
  ["HKG", "Emmer Pizza, Bar & Cafe", "7E124-7E840-7E842", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "veget|weste", "vegetarian|western", "07:00 - 01:30", false, 22.315310149283995, 113.93316351165788],
  ["HKG", "Tong Kee Bao Dim", "3TL017", "T2", "T2", "L3", "Terminal 2", "", false, "Non-restricted Area", "explicit", "baker|chine|fastf", "bakery|chinese|fast_food", "07:00 - 23:00", false, 22.315791407295276, 113.93707693452998],
  ["HKG", "SAFFRON", "dining_desse_00013", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "desse|halal|veget", "dessert|halal|vegetarian", "06:00 - 00:00", false, 22.315311317214068, 113.93564597162452],
  ["HKG", "Tasty Congee & Noodle Wantun Shop", "7E182", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "chine", "chinese", "00:00 - 24:00", true, 22.315570653659833, 113.93395871277704],
  ["HKG", "Yukimura", "7TL036", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "asian", "asian", "00:00 - 24:00", true, 22.316931161597637, 113.9393261622583],
  ["HKG", "Joy Full House", "7TL353", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "desse|weste", "dessert|western", "00:00 - 24:00", true, 22.317046628790262, 113.93924635941192],
  ["HKG", "Sang Roastery", "7TL039", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "weste", "western", "06:00 - 23:00", false, 22.316848215202125, 113.93917896474017],
  ["HKG", "Ho Fan Ho Sung", "3TL158", "T2", "T2", "L3", "Terminal 2", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "07:00 - 23:00", false, 22.315852495894326, 113.9370529657047],
  ["HKG", "Ufufu Cafe", "7TL035", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "desse|weste", "dessert|western", "00:00 - 24:00", true, 22.317003392499252, 113.9392944217653],
  ["HKG", "2 Cafe", "8T006", "T1", "T1", "L8", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine", "chinese", "05:00 - 23:00", false, 22.314963837884683, 113.93462275042558],
  ["HKG", "HUNG FOOK TONG", "7T087", "T1", "T1", "L7", "Terminal 1", "", false, "Non-restricted Area", "explicit", "desse|veget", "dessert|vegetarian", "00:00 - 24:00", true, 22.315371, 113.934481],
  ["HKG", "OldTown White Coffee", "6W564D", "T1", "T1", "L6", "Terminal 1", "40-80", true, "Restricted Area", "explicit", "asian|fastf|halal|veget", "asian|fast_food|halal|vegetarian", "07:00 - 23:00 (Last order: 22:30)", false, 22.312524, 113.927046],
  ["HKG", "Blue Bottle Coffee", "7E143", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.314109105059952, 113.93419798989696],
  ["HKG", "Luckin Coffee", "3TL056", "T2", "T2", "L3", "Terminal 2", "", false, "Non-restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.316633215969553, 113.93676253136391],
  ["HKG", "hana-musubi", "5T194", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.315925259280746, 113.93541055633759],
  ["HKG", "Super Super Congee and Noodles", "5E538C", "T1", "T1", "L5", "Terminal 1", "", true, "Restricted Area", "explicit", "chine|fastf|veget", "chinese|fast_food|vegetarian", "06:00 - 23:00", false, 22.314671, 113.9337],
  ["HKG", "Sushi & Sake Bar Taka", "7E187A", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "asian|fastf", "asian|fast_food", "06:00 - 20:30", false, 22.315123, 113.934088],
  ["HKG", "Nap Tea", "7TL052", "T2", "T2", "L7", "Terminal 2", "", false, "Non-restricted Area", "explicit", "desse|weste", "dessert|western", "06:00 – 23:00", false, 22.316702241290827, 113.93922960841246],
  ["HKG", "A-1 Bakery Express", "6MC151A", "T1", "T1", "L6", "Midfield Concourse", "201-230", true, "Restricted Area", "explicit", "baker", "bakery", "07:00 - 23:00", false, 22.309660201470088, 113.91774882894158],
  ["HKG", "A-1 Bakery Express", "7T098", "T1", "T1", "L7", "Terminal 1", "", false, "Non-restricted Area", "explicit", "baker", "bakery", "07:00 - 23:00", false, 22.31508037371818, 113.9347628216064],
  ["HKG", "The Forest Bakery", "7E126C", "T1", "T1", "L7", "Terminal 1", "", true, "Restricted Area", "explicit", "baker", "bakery", "07:00 - 23:00", false, 22.315853206383334, 113.93355844820121],
  ["HKG", "FINEPRINT", "dining_asian_00015", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "weste", "western", "06:00 – 23:00", false, 22.314437072308984, 113.93632315696713],
  ["HKG", "Crystal Jade La Mian Xiao Long Bao", "cj_dining_260105_001", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "chine|veget", "chinese|vegetarian", "07:00 - 23:30", false, 22.315350895899584, 113.93602593698841],
  ["HKG", "Chi Cha San Chen", "dining_weste_00021", "T1", "T1", "L6", "Terminal 1", "11", true, "Restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.3145905555417, 113.93270841694417],
  ["HKG", "THE ALCHEMIST CAFE", "5T150", "T1", "T1", "L5", "Terminal 1", "", false, "Non-restricted Area", "explicit", "weste", "western", "06:00 - 24:00 (Last order 23:00)", false, 22.316092590198465, 113.93578054018272],
  ["HKG", "Chagee", "dining_weste_00020", "T1", "T1", "L6", "Terminal 1", "30", true, "Restricted Area", "explicit", "weste", "western", "07:00 - 23:00", false, 22.313917879193756, 113.93007826047099],
];

const FIELDS = ['airport', 'name', 'sourceId', 'terminalRaw', 'terminal', 'level', 'area', 'gateHint', 'isAirside', 'securityRaw', 'securityBasis', 'categoryRaw', 'category', 'hoursRaw', 'is24H', 'lat', 'lon'] as const;

// BUILT ONCE, LAZILY. The rows are the storage format; this is the shape the
// screen reads. Nothing here runs until something asks for dining.
let cache: Dining[] | null = null;

export function allDining(): Dining[] {
  if (cache !== null) return cache;
  cache = ROWS.map(r => {
    const o: any = {};
    FIELDS.forEach((f, i) => { o[f] = r[i]; });
    return o as Dining;
  });
  return cache;
}

// EVERYTHING AT ONE AIRPORT. The caller filters by terminal and by isAirside,
// because only the caller knows whether this passenger has cleared security.
export function diningAt(iata: string): Dining[] {
  const code = iata.toUpperCase();
  return allDining().filter(d => d.airport === code);
}
